package com.chaekdojang.api.global.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

    REVIEW_NOT_FOUND(HttpStatus.NOT_FOUND, "독후감을 찾을 수 없습니다."),
    INVALID_REREAD_SOURCE(HttpStatus.BAD_REQUEST, "본인의 같은 책 독후감만 재독 기록으로 연결할 수 있습니다."),
    REREAD_ALREADY_EXISTS(HttpStatus.CONFLICT, "이 기록에서 이어진 재독 독후감이 이미 있습니다."),
    REREAD_BOOK_CHANGE_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "재독 기록으로 연결된 독후감은 책을 변경할 수 없습니다."),
    INVALID_REVIEW_LINK(HttpStatus.BAD_REQUEST, "재독 기록과 다른 독후감 이어쓰기를 동시에 연결할 수 없습니다."),
    INVALID_CONTINUATION_SOURCE(HttpStatus.BAD_REQUEST, "다른 사용자의 공개된 같은 책 독후감에서만 이어쓸 수 있습니다."),
    BLOCKED_REVIEW_CONNECTION(HttpStatus.FORBIDDEN, "차단 관계인 사용자의 독후감에는 이어쓸 수 없습니다."),
    CONNECTED_REVIEW_BOOK_CHANGE_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "다른 기록과 연결된 독후감은 책을 변경할 수 없습니다."),
    BOOK_NOT_FOUND(HttpStatus.NOT_FOUND, "책을 찾을 수 없습니다."),
    NICKNAME_ALREADY_EXISTS(HttpStatus.CONFLICT, "이미 사용 중인 닉네임입니다."),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "사용자를 찾을 수 없습니다."),
    FORBIDDEN(HttpStatus.FORBIDDEN, "접근 권한이 없습니다."),
    CANNOT_FOLLOW_SELF(HttpStatus.BAD_REQUEST, "자기 자신을 팔로우할 수 없습니다."),
    FOLLOW_ALREADY_EXISTS(HttpStatus.CONFLICT, "이미 팔로우한 사용자입니다."),
    FOLLOW_NOT_FOUND(HttpStatus.NOT_FOUND, "팔로우 관계가 존재하지 않습니다."),
    LIKE_ALREADY_EXISTS(HttpStatus.CONFLICT, "이미 좋아요한 독후감입니다."),
    LIKE_NOT_FOUND(HttpStatus.NOT_FOUND, "좋아요 기록이 없습니다."),
    COMMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "댓글을 찾을 수 없습니다."),
    LIBRARY_ALREADY_EXISTS(HttpStatus.CONFLICT, "이미 서재에 있는 책입니다."),
    LIBRARY_NOT_FOUND(HttpStatus.NOT_FOUND, "서재 항목을 찾을 수 없습니다."),
    BOOKMARK_ALREADY_EXISTS(HttpStatus.CONFLICT, "이미 저장한 독후감입니다."),
    BOOKMARK_NOT_FOUND(HttpStatus.NOT_FOUND, "저장 기록이 없습니다."),
    NOTIFICATION_NOT_FOUND(HttpStatus.NOT_FOUND, "알림을 찾을 수 없습니다."),
    CHAT_ROOM_NOT_FOUND(HttpStatus.NOT_FOUND, "채팅방을 찾을 수 없습니다."),
    TRANSLATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "번역에 실패했습니다."),
    FEEDBACK_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "도장 코멘트를 만들지 못했습니다. 잠시 후 다시 시도해주세요."),
    FEEDBACK_DISABLED(HttpStatus.SERVICE_UNAVAILABLE, "도장 코멘트 기능을 잠시 이용할 수 없습니다."),
    FEEDBACK_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "오늘 도장 코멘트를 모두 사용했습니다."),
    AI_REFLECTION_DISABLED(HttpStatus.SERVICE_UNAVAILABLE, "AI 회고 기능을 잠시 이용할 수 없습니다."),
    AI_REFLECTION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "AI 회고를 만들지 못했습니다. 기존 독후감은 그대로 보관됩니다."),
    AI_REFLECTION_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "오늘 사용할 수 있는 AI 회고 횟수를 모두 사용했습니다."),
    FOLLOW_UP_QUESTION_NOT_FOUND(HttpStatus.NOT_FOUND, "저장된 후속 질문이 없습니다."),
    CHANGE_COMPARISON_NOT_AVAILABLE(HttpStatus.BAD_REQUEST, "비교할 수 있는 활성 재독 기록이 없습니다."),
    CHANGE_COMPARISON_NOT_FOUND(HttpStatus.NOT_FOUND, "저장된 생각 변화 비교가 없습니다."),
    GROUP_QUESTION_NOT_FOUND(HttpStatus.NOT_FOUND, "독서모임 질문을 찾을 수 없습니다."),
    GROUP_QUESTION_NOT_PUBLISHED(HttpStatus.BAD_REQUEST, "아직 공개되지 않은 질문에는 답할 수 없습니다."),
    GROUP_QUESTION_RESPONSE_NOT_FOUND(HttpStatus.NOT_FOUND, "저장된 중간 응답이 없습니다."),
    GROUP_BOOK_ARCHIVED(HttpStatus.BAD_REQUEST, "완료된 함께 읽기에서는 새 질문이나 중간 응답을 남길 수 없습니다."),
    GROUP_QUESTION_AI_DISABLED(HttpStatus.SERVICE_UNAVAILABLE, "AI 질문 제안 기능을 잠시 이용할 수 없습니다."),
    GROUP_QUESTION_AI_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "AI 질문 초안을 만들지 못했습니다. 기존 모임 기록은 그대로 보관됩니다."),
    GROUP_QUESTION_AI_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "오늘 사용할 수 있는 AI 제안 횟수를 모두 사용했습니다."),
    GROUP_ANALYSIS_NOT_ENOUGH_REVIEWS(HttpStatus.BAD_REQUEST, "모임 전체 분석에는 연결된 독후감이 2개 이상 필요합니다."),
    GROUP_ANALYSIS_AI_DISABLED(HttpStatus.SERVICE_UNAVAILABLE, "모임 AI 분석 기능을 잠시 이용할 수 없습니다."),
    GROUP_ANALYSIS_AI_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "모임 AI 분석을 만들지 못했습니다. 기존 결과는 그대로 보관됩니다."),
    GROUP_ANALYSIS_AI_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "오늘 사용할 수 있는 AI 분석 횟수를 모두 사용했습니다."),
    SUBSCRIPTION_ALREADY_EXISTS(HttpStatus.CONFLICT, "이미 구독 중입니다."),
    SUBSCRIPTION_NOT_FOUND(HttpStatus.NOT_FOUND, "구독 정보를 찾을 수 없습니다."),
    CAMPAIGN_NOT_FOUND(HttpStatus.NOT_FOUND, "서평단 캠페인을 찾을 수 없습니다."),
    CAMPAIGN_NOT_RECRUITING(HttpStatus.BAD_REQUEST, "지금은 신청을 받지 않는 캠페인입니다."),
    CAMPAIGN_ALREADY_APPLIED(HttpStatus.CONFLICT, "이미 신청한 캠페인입니다."),
    CAMPAIGN_APPLICATION_NOT_FOUND(HttpStatus.NOT_FOUND, "서평단 신청 내역을 찾을 수 없습니다."),
    CAMPAIGN_NOT_SELECTED(HttpStatus.BAD_REQUEST, "선정된 신청만 독후감을 제출할 수 있습니다."),
    CAMPAIGN_REVIEW_BOOK_MISMATCH(HttpStatus.BAD_REQUEST, "캠페인 도서로 작성한 독후감만 제출할 수 있습니다."),
    CAMPAIGN_INVALID_PERIOD(HttpStatus.BAD_REQUEST, "모집 시작·마감·독후감 마감 순서가 올바르지 않습니다."),
    CAMPAIGN_STATUS_TRANSITION_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "현재 상태에서는 변경할 수 없는 단계입니다."),
    CAMPAIGN_PRIORITY_INVITE_ONLY(HttpStatus.FORBIDDEN, "아직 관심 독자 우선 신청 기간입니다. 공개 모집이 시작되면 신청할 수 있습니다."),
    CONSENT_TERMS_REQUIRED(HttpStatus.BAD_REQUEST, "서평단 참여 약관에 동의해야 신청할 수 있습니다."),
    CONSENT_NOT_FOUND(HttpStatus.NOT_FOUND, "동의 내역을 찾을 수 없습니다."),
    EXPORT_FORMAT_NOT_SUPPORTED(HttpStatus.BAD_REQUEST, "지원하지 않는 내보내기 형식입니다."),
    CAMPAIGN_NOT_EBOOK(HttpStatus.BAD_REQUEST, "전자책 배본 캠페인에서만 쓸 수 있는 기능입니다."),
    EBOOK_FILE_INVALID(HttpStatus.BAD_REQUEST, "PDF 파일만 올릴 수 있습니다."),
    EBOOK_FILE_TOO_LARGE(HttpStatus.BAD_REQUEST, "전자책 파일은 50MB 이하만 올릴 수 있습니다."),
    EBOOK_FILE_NOT_UPLOADED(HttpStatus.NOT_FOUND, "아직 전자책 파일이 올라오지 않았습니다."),
    EBOOK_ACCESS_DENIED(HttpStatus.FORBIDDEN, "이 전자책을 열람할 권한이 없습니다."),
    EBOOK_ACCESS_EXPIRED(HttpStatus.GONE, "전자책 열람 기간이 끝났습니다."),
    EBOOK_ACCESS_REVOKED(HttpStatus.FORBIDDEN, "전자책 열람 권한이 회수되었습니다."),
    EBOOK_WATERMARK_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "전자책을 준비하지 못했습니다. 잠시 후 다시 시도해주세요."),
    EBOOK_STORAGE_NOT_CONFIGURED(HttpStatus.SERVICE_UNAVAILABLE, "전자책 저장소가 설정되지 않아 PDF 서평단을 이용할 수 없습니다."),
    NOT_FOUND(HttpStatus.NOT_FOUND, "찾을 수 없습니다."),
    INVALID_REQUEST(HttpStatus.BAD_REQUEST, "잘못된 요청입니다.");

    private final HttpStatus status;
    private final String message;
}
