--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: access_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.access_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    elapsed_ms bigint NOT NULL,
    ip character varying(50) NOT NULL,
    method character varying(10) NOT NULL,
    status integer NOT NULL,
    uri character varying(500) NOT NULL
);


--
-- Name: access_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.access_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.access_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: books; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.books (
    id bigint NOT NULL,
    author character varying(255) NOT NULL,
    category character varying(100),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    isbn13 character varying(13) NOT NULL,
    publisher character varying(255),
    source character varying(20) NOT NULL,
    thumbnail character varying(255),
    title character varying(255) NOT NULL,
    CONSTRAINT books_source_check CHECK (((source)::text = ANY ((ARRAY['KAKAO'::character varying, 'GOOGLE_BOOKS'::character varying])::text[])))
);


--
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    content character varying(1000) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    chat_room_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


--
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_rooms (
    id bigint NOT NULL,
    book_id bigint NOT NULL
);


--
-- Name: chat_rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    author_id bigint NOT NULL,
    review_id bigint NOT NULL
);


--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: error_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.error_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    exception_type character varying(200) NOT NULL,
    ip character varying(50),
    level character varying(20) NOT NULL,
    message character varying(1000) NOT NULL,
    method character varying(10) NOT NULL,
    status integer NOT NULL,
    uri character varying(500) NOT NULL,
    user_id bigint
);


--
-- Name: error_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.error_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.error_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: follows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.follows (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    follower_id bigint NOT NULL,
    following_id bigint NOT NULL
);


--
-- Name: follows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.follows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.follows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inquiries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inquiries (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    guest_name character varying(255),
    guest_email character varying(255),
    user_id bigint,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    deleted_at timestamp without time zone
);


--
-- Name: inquiries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.inquiries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: inquiries_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.inquiries_id_seq OWNED BY public.inquiries.id;


--
-- Name: inquiry_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inquiry_comments (
    id bigint NOT NULL,
    inquiry_id bigint NOT NULL,
    author_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp without time zone NOT NULL
);


--
-- Name: inquiry_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.inquiry_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: inquiry_comments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.inquiry_comments_id_seq OWNED BY public.inquiry_comments.id;


--
-- Name: libraries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.libraries (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    book_id bigint NOT NULL,
    user_id bigint NOT NULL,
    completed_at date,
    CONSTRAINT libraries_status_check CHECK (((status)::text = ANY ((ARRAY['READING'::character varying, 'FINISHED'::character varying, 'WISHLIST'::character varying])::text[])))
);


--
-- Name: libraries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.libraries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.libraries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metric_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.metric_events (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    device character varying(80),
    duration_ms bigint NOT NULL,
    event_type character varying(50) NOT NULL,
    ip character varying(50),
    path character varying(500) NOT NULL,
    referrer character varying(500),
    session_id character varying(80) NOT NULL,
    user_id bigint
);


--
-- Name: metric_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.metric_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metric_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    target_id bigint,
    type character varying(255) NOT NULL,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['LIKE'::character varying, 'COMMENT'::character varying, 'FOLLOW'::character varying])::text[])))
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchase_links (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    provider character varying(20) NOT NULL,
    url character varying(255) NOT NULL,
    book_id bigint NOT NULL,
    CONSTRAINT purchase_links_provider_check CHECK (((provider)::text = ANY ((ARRAY['COUPANG'::character varying, 'KYOBO'::character varying])::text[])))
);


--
-- Name: purchase_links_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.purchase_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_bookmarks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_bookmarks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    review_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: review_bookmarks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review_bookmarks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_bookmarks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_likes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    review_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: review_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    rating integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    author_id bigint NOT NULL,
    book_id bigint,
    hidden boolean DEFAULT false NOT NULL,
    CONSTRAINT reviews_rating_check CHECK (((rating <= 5) AND (rating >= 1)))
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscriptions (
    id bigint NOT NULL,
    active boolean NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    payment_key character varying(255),
    plan character varying(255) NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT subscriptions_plan_check CHECK (((plan)::text = ANY ((ARRAY['MONTHLY'::character varying, 'YEARLY'::character varying])::text[])))
);


--
-- Name: subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_auth_providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_auth_providers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    provider character varying(10) NOT NULL,
    provider_email character varying(255),
    provider_profile_image character varying(255),
    provider_user_id character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_auth_providers_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'KAKAO'::character varying, 'NAVER'::character varying, 'GOOGLE'::character varying])::text[])))
);


--
-- Name: user_auth_providers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_auth_providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_auth_providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    bio text,
    country character varying(10) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    email character varying(255),
    language character varying(10) NOT NULL,
    nickname character varying(255) NOT NULL,
    profile_image character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    role character varying(15) DEFAULT 'USER'::character varying NOT NULL,
    life_book_id bigint
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inquiries id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiries ALTER COLUMN id SET DEFAULT nextval('public.inquiries_id_seq'::regclass);


--
-- Name: inquiry_comments id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiry_comments ALTER COLUMN id SET DEFAULT nextval('public.inquiry_comments_id_seq'::regclass);


--
-- Name: access_logs access_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_logs
    ADD CONSTRAINT access_logs_pkey PRIMARY KEY (id);


--
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- Name: chat_rooms chat_rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT chat_rooms_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: error_logs error_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.error_logs
    ADD CONSTRAINT error_logs_pkey PRIMARY KEY (id);


--
-- Name: follows follows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follows
    ADD CONSTRAINT follows_pkey PRIMARY KEY (id);


--
-- Name: inquiries inquiries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiries
    ADD CONSTRAINT inquiries_pkey PRIMARY KEY (id);


--
-- Name: inquiry_comments inquiry_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiry_comments
    ADD CONSTRAINT inquiry_comments_pkey PRIMARY KEY (id);


--
-- Name: libraries libraries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.libraries
    ADD CONSTRAINT libraries_pkey PRIMARY KEY (id);


--
-- Name: metric_events metric_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metric_events
    ADD CONSTRAINT metric_events_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: purchase_links purchase_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_links
    ADD CONSTRAINT purchase_links_pkey PRIMARY KEY (id);


--
-- Name: review_bookmarks review_bookmarks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_bookmarks
    ADD CONSTRAINT review_bookmarks_pkey PRIMARY KEY (id);


--
-- Name: review_likes review_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_likes
    ADD CONSTRAINT review_likes_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: subscriptions subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);


--
-- Name: users uk2ty1xmrrgtn89xt7kyxx6ta7h; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk2ty1xmrrgtn89xt7kyxx6ta7h UNIQUE (nickname);


--
-- Name: follows uk4faelgsm2rxl2jf3iyjy981ro; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follows
    ADD CONSTRAINT uk4faelgsm2rxl2jf3iyjy981ro UNIQUE (follower_id, following_id);


--
-- Name: chat_rooms uk5rh2q7g32xt1a82s73nku9ag; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT uk5rh2q7g32xt1a82s73nku9ag UNIQUE (book_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: review_bookmarks uk8bmm1ark2mh6qakxnkondppov; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_bookmarks
    ADD CONSTRAINT uk8bmm1ark2mh6qakxnkondppov UNIQUE (review_id, user_id);


--
-- Name: review_likes ukb74o5l2fmrgqg556d9nyop0ns; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_likes
    ADD CONSTRAINT ukb74o5l2fmrgqg556d9nyop0ns UNIQUE (review_id, user_id);


--
-- Name: libraries ukh802lkem4xip1tolseiwng3dq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.libraries
    ADD CONSTRAINT ukh802lkem4xip1tolseiwng3dq UNIQUE (user_id, book_id);


--
-- Name: books uksesykpxp69k5u88p4654qsdo0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT uksesykpxp69k5u88p4654qsdo0 UNIQUE (isbn13);


--
-- Name: user_auth_providers uq_provider_user_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_auth_providers
    ADD CONSTRAINT uq_provider_user_id UNIQUE (provider, provider_user_id);


--
-- Name: user_auth_providers user_auth_providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_auth_providers
    ADD CONSTRAINT user_auth_providers_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_chat_messages_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_messages_created_at ON public.chat_messages USING btree (created_at);


--
-- Name: idx_chat_messages_room_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_messages_room_id ON public.chat_messages USING btree (chat_room_id);


--
-- Name: idx_metric_events_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_metric_events_created_at ON public.metric_events USING btree (created_at);


--
-- Name: idx_metric_events_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_metric_events_session_id ON public.metric_events USING btree (session_id);


--
-- Name: idx_metric_events_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_metric_events_user_id ON public.metric_events USING btree (user_id);


--
-- Name: notifications fk13vcnq3ukas06ho1yrbc5lrb5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk13vcnq3ukas06ho1yrbc5lrb5 FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: user_auth_providers fk36nn9pmlugyb6c34h3vakuai; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_auth_providers
    ADD CONSTRAINT fk36nn9pmlugyb6c34h3vakuai FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reviews fk6a9k6xvev80se5rreqvuqr7f9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk6a9k6xvev80se5rreqvuqr7f9 FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: review_bookmarks fk797dt9bvyey3fp5l5stv0khe0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_bookmarks
    ADD CONSTRAINT fk797dt9bvyey3fp5l5stv0khe0 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: review_bookmarks fk7iyxdutykqlmthmuqi3agxvn5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_bookmarks
    ADD CONSTRAINT fk7iyxdutykqlmthmuqi3agxvn5 FOREIGN KEY (review_id) REFERENCES public.reviews(id);


--
-- Name: chat_rooms fk9d26e9kn115shiqpqf4loo4mw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT fk9d26e9kn115shiqpqf4loo4mw FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: notifications fk9kxl0whvhifo6gw4tjq36v53k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9kxl0whvhifo6gw4tjq36v53k FOREIGN KEY (receiver_id) REFERENCES public.users(id);


--
-- Name: libraries fk9o3aof433waq4oq9od7qfq0ah; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.libraries
    ADD CONSTRAINT fk9o3aof433waq4oq9od7qfq0ah FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: chat_messages fkbcsxusjp1v4rd8879fhvq8ssb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkbcsxusjp1v4rd8879fhvq8ssb FOREIGN KEY (chat_room_id) REFERENCES public.chat_rooms(id);


--
-- Name: comments fkdpo60i7auk5cudv7kkny8jrqb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkdpo60i7auk5cudv7kkny8jrqb FOREIGN KEY (review_id) REFERENCES public.reviews(id);


--
-- Name: purchase_links fkf5ha7p0swo43bctv6na81g8kt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_links
    ADD CONSTRAINT fkf5ha7p0swo43bctv6na81g8kt FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: chat_messages fkgiqeap8ays4lf684x7m0r2729; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkgiqeap8ays4lf684x7m0r2729 FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: users fkgwayr1r8tfpev9u14vch3af5i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkgwayr1r8tfpev9u14vch3af5i FOREIGN KEY (life_book_id) REFERENCES public.books(id);


--
-- Name: subscriptions fkhro52ohfqfbay9774bev0qinr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fkhro52ohfqfbay9774bev0qinr FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: libraries fkii9s3dpbrehajshdirhol0asr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.libraries
    ADD CONSTRAINT fkii9s3dpbrehajshdirhol0asr FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: review_likes fkm2uonfg8ky6jwtu6iugkilox8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_likes
    ADD CONSTRAINT fkm2uonfg8ky6jwtu6iugkilox8 FOREIGN KEY (review_id) REFERENCES public.reviews(id);


--
-- Name: comments fkn2na60ukhs76ibtpt9burkm27; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkn2na60ukhs76ibtpt9burkm27 FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: review_likes fknual15vv88tiqnwmi60tb2l8d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_likes
    ADD CONSTRAINT fknual15vv88tiqnwmi60tb2l8d FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: follows fkonkdkae2ngtx70jqhsh7ol6uq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follows
    ADD CONSTRAINT fkonkdkae2ngtx70jqhsh7ol6uq FOREIGN KEY (following_id) REFERENCES public.users(id);


--
-- Name: follows fkqnkw0cwwh6572nyhvdjqlr163; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follows
    ADD CONSTRAINT fkqnkw0cwwh6572nyhvdjqlr163 FOREIGN KEY (follower_id) REFERENCES public.users(id);


--
-- Name: reviews fkse5kx11600wtv0jh9jobvrdpi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkse5kx11600wtv0jh9jobvrdpi FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: metric_events fksvrkdjx45wrevp2tf6penr9vb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metric_events
    ADD CONSTRAINT fksvrkdjx45wrevp2tf6penr9vb FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: inquiries inquiries_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiries
    ADD CONSTRAINT inquiries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: inquiry_comments inquiry_comments_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiry_comments
    ADD CONSTRAINT inquiry_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: inquiry_comments inquiry_comments_inquiry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiry_comments
    ADD CONSTRAINT inquiry_comments_inquiry_id_fkey FOREIGN KEY (inquiry_id) REFERENCES public.inquiries(id);


--
-- PostgreSQL database dump complete
--


