CREATE TABLE IF NOT EXISTS public.admin_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id bigint REFERENCES public.users(id),
    action character varying(100) NOT NULL,
    target_type character varying(50) NOT NULL,
    target_id bigint,
    summary character varying(1000) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_created_at
    ON public.admin_audit_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_action_created_at
    ON public.admin_audit_logs (action, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_target
    ON public.admin_audit_logs (target_type, target_id);

CREATE INDEX IF NOT EXISTS idx_access_logs_created_at
    ON public.access_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_access_logs_method_status_created_at
    ON public.access_logs (method, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_error_logs_created_at
    ON public.error_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_error_logs_level_status_created_at
    ON public.error_logs (level, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_reviews_feed
    ON public.reviews (hidden, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_reviews_author_created_at
    ON public.reviews (author_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_reviews_book_created_at
    ON public.reviews (book_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_comments_review_created_at
    ON public.comments (review_id, created_at)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_follows_following_created_at
    ON public.follows (following_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_follows_follower_created_at
    ON public.follows (follower_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_receiver_created_at
    ON public.notifications (receiver_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_receiver_unread
    ON public.notifications (receiver_id)
    WHERE is_read = false;

CREATE INDEX IF NOT EXISTS idx_libraries_user_updated_at
    ON public.libraries (user_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_libraries_user_status_updated_at
    ON public.libraries (user_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_books_title
    ON public.books (title);

CREATE INDEX IF NOT EXISTS idx_books_author
    ON public.books (author);
