CREATE TABLE IF NOT EXISTS public.admin_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id bigint REFERENCES public.users(id),
    action character varying(100) NOT NULL,
    target_type character varying(50) NOT NULL,
    target_id bigint,
    summary character varying(1000) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_created_at
    ON public.admin_audit_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_action_created_at
    ON public.admin_audit_logs (action, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_target
    ON public.admin_audit_logs (target_type, target_id);
